### ISSUE TITLE
for loop for phrases

### ISSUE THREAD

**Issue by basma6** [Mishra-Shreya/Sanket#2]
hello, i have a small issue i can't make a for loop to understand a phrase (words separated by a space) like how old are you , i can't make my code understand the space how can i do this please??
and what could be the reason for running my app in chrome and it works fine and when i try it on my android mobile the button for listening don't work although i allowed the usage of mic
thank you

**Comment by Mishra-Shreya** [comment]
Answer to 1st question : There are many ways to detect a phrase in a sentence. You may create a list of all the phrases and then loop through that list to check if phrase appears in the voice content. Currently, for simplicity I've extracted alphabets from the voice command. Thus the above logic should be applied before splitting the sentence.
Answer to 2nd question : See the runtime logs to navigate to the exact issue. (It should've worked fine if all the permissions were granted)
